[WIP] SplitMongo Pruning
openedx-unsupported/tubular pull request #184
Opened 2017-08-10 03:56 UTC by eltoncarr

> ### This is work in progress

This PR introduces initial code for handling splitmongo pruning. 

**Core capabilities currently available**:
1. querying specified edxapp database active_versions and structures collections 
2. identifying all structures that can be removed
3. removing identified structures

All capabilities above are supported for both 
1. live (ie: actual database interaction) 
2. static (using test data)

**Although functional, do not run this against a live database.**

Additional capabilities that are in progress (or targeted):
1. addressing performance concerns about pulling all documents in active_versions and structures collections at once
2. enabling visualization of sample course/library structures before and after pruning

**Known Issues**:
1. this script is proven to work against the **ginko" release

2017-08-11 14:02 UTC, ormsbee commented
I realize this is a WIP, but I'm curious -- what in particular makes this incompatible with Ginkgo?

2017-08-11 18:36 UTC, eltoncarr commented
@ormsbee , regarding Ginkgo, we had done an initial run about 1 month ago, saw the failure but did not explore it further. We instead opted for getting the script fully operational for Ficus. We re-validated this morning and had no issues. I will remove the limitation.

2017-08-11 20:40 UTC, doctoryes reviewed
@eltoncarr Thanks for submitting this code! It's headed in the right direction.

2017-08-11 20:40 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +    help=u'name of the edx database to prune'
`Name of the Open edX MongoDB database to prune`? The current help is vague without needed context.

2017-08-11 20:40 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +)
Is this option needed? I think we'd always want to re-link the structures.

2017-08-11 20:40 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +)
A better test strategy would be to move the util code that performs the pruning out of the actual click script. Then test that separated util code separately with test data. It'd keep the script below having a single purpose. Many of the other scripts in this repo do the same - the script itself handles validating parameters and then calls the specific utility code in other modules. This strategy also makes the utility code callable from other useful locations.

2017-08-11 20:40 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +)
Ditto.

2017-08-11 20:40 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +            active_versions.append(active_version_doc)
Why this looping check? Is it possible that none of these `fields` will be present?

2017-08-11 20:40 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +
Ah - I see. Unless I hear a convincing case from someone, I vote for re-linking.

2017-08-11 20:40 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +    return structures_list
`return list(resultset)`?

2017-08-11 20:40 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +    # TODO: (performance): chunk up the removals to minimize possible production impact
I agree. The script should ultimately be tested on a large course with many edits/structures in its history.

2017-08-11 20:40 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +                    LOG.debug(status_message.format(
Nit: Most of your log.debugs should be log.info - they're important! 😄

2017-08-11 21:05 UTC, ormsbee commented
I'm starting on this review now. Is the plan to get the basic functionality merged in first and then address performance and visualization issues later? Or is it your intention for this PR to eventually cover all that functionality? I have a mild preference for the former, but either is fine -- I'm just trying to make sure I understand the intended scope here.

Thank you.

2017-08-11 22:46 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +)
We've had ongoing discussions about the need for re-linking structures to origin. Given the conversations, we made this optional. Additionally, there is an additional overhead for re-linking (primarily the batch update needed post-pruning). If necessary, we can default it to true instead.

2017-08-11 22:47 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +            active_versions.append(active_version_doc)
Yes. Libraries don't have [draft|published]-branch for example.

2017-08-11 22:47 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    return structures_list
structures_list is already a list

2017-08-11 22:47 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    # TODO: (performance): chunk up the removals to minimize possible production impact
That's the target of our next iteration. First focus was correctness. Accounting for performance is next.

2017-08-11 22:47 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +
Agreed. See comments above

2017-08-11 22:48 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +                    LOG.debug(status_message.format(
Certainly.

2017-08-11 22:48 UTC, eltoncarr commented
The essence of this PR was to get validation of the approach, just covering a very basic case. With that initial indication of correctness. We assumed there are other aspects we may not be privy to and have not accounted for (examples: how pruning impacts e-commerce, insight, mysql "snapshots" or related other components). 

With confirmation of the most basic case, we'd iterate further wrt performance and other concerns that may come up. Therefore, it seems easier to start with the basic concerns first (first round of review) and layer on performance, visualization, enabling single course/library pruning (in a subsequent review). This is my current preference. 

However, like you, I am also open to adding the additional pieces and get them all reviewed once and pushed once as one complete feature. If you feel otherwise, do let me know. If not, let's proceed with the basics first and follow up with other concerns.

2017-08-12 14:09 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    help=u'name of the edx database to prune'
- [ ] Improve option message for the database name option

2017-08-13 04:22 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +)
- [ ] Move support functions into utility class

2017-08-13 05:25 UTC, ormsbee requested changes
Thank you so much for taking this on! I'm done with my first pass. Please note that the items marked nitpicks are intended to be optional -- they're mostly small suggestions to simplify the code or make it more idiomatically Python.

Some high level concerns:

1. The specific MongoDB serialized representation bleeds through into the functions, making it harder to understand.

I realize in some cases this is unavoidable. `get_active_verisions()` needs to understand MongoDB serialization internals. But it currently returns the serialized active_versions docs rather than just the data it needs, so other methods have to know that it's a dictionary with a `versions` key, and inside of that it has one of the `TARGET_ACTIVE_VERSIONS_KEYS`...

The abstract problem space we're dealing with is making a tree and pruning it. I think that it would greatly help future maintainers understand what's going on if we deserialize from MongoDB (and the static file) in as small and isolated a layer as possible so we can immediately get back those simple objects where we do all our interesting work. Once we've determined the list of structure IDs that need deleting or relinking, we can send a simple list of those IDs back to the backend layer, and have it worry about the details of the serialized format.

2. We have some places where it looks like we're doing O(n)^2 operations on the number of structures, which could cause us trouble down the road.

I realize that we're not aiming to be performant with this PR, so I'm not going to gate this PR on addressing these issues. I just want to flag a few cases where I'm seeing this, to inform future work.

Thank you!

2017-08-13 05:25 UTC, ormsbee commented on tubular/tests/test_prune_modulestore.py
> +        assert isinstance(file_exists, object)
What is the purpose of this assertion?

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +        structure_filter = get_structures_filter(active_versions_list)
Is this redundant? Do we ever send `active_versions_list` but have `filter_enabled` be `False`?

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    return structures_list
I think what @doctoryes means that that:

```python
structures_list = []
for structure_doc in resultset:
    structures_list.append(structure_doc)

return structures_list
```

Is equivalent to:

```python
return list(resultset)
```

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +
Nitpick: Python idiom is to use the falsiness of empty lists, and do something more like:

```python
if not structures_to_remove:
    return
```

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +        structures_removal_filter['$in'].append(ObjectId(structure_objectid_str))
Nitpick: Might be a little clearer as a comprehension.

```python
structures_removal_filter = {
    '$in': [ObjectId(oid) for oid in structures_to_remove]
}

2017-08-13 05:25 UTC, ormsbee commented on tubular/tests/test_prune_modulestore.py
> +        self.remove_output_file()
FWIW, the [`tempfile`](https://docs.python.org/2/library/tempfile.html) package can help with the management of short lived files for testing (or other purposes).

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +        LOG.debug("{0} active versions identified.".format(len(active_versions)))
Nitpick: With logging, the preferred way to do string formatting would look like:

```python
LOG.debug("%s active versions identified", len(active_versions))
```

This allows certain smart log aggregators to group log messages together, where using the `"{0}"` style of format string does the text substitution before the logging system can see it.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +        filter_enabled = (active_version_filter is not None and len(active_versions) > 0)
Nitpick: Using truthiness of values, I think you can write this out as:

```python
filter_enabled = active_version_filter and active_versions
```

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +            active_versions.append(active_version_doc)
Sorry, I don't quite understand that. What active_versions_docs would be excluded by this if statement?

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +        active_version_filter = get_active_version_filter(active_version_list)
Nitpick: This might read more clearly if `get_active_version_filter` returned `{}` when it got a `None` for a `active_version_list`. So the above three lines becomes:

```python
    active_version_filter = get_active_version_filter(active_version_list)
```

And the actual call for the result set loses the conditional and just becomes:

```python
    resultset = db.modulestore.active_versions.find(active_version_filter, fields)
```

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    """
What is the intended behavior of this method if an empty list is passed as the argument? Should it return a filter that will get everything? Nothing? Error?

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +TARGET_ACTIVE_VERSIONS_KEYS = [u'library', u'draft-branch', u'published-branch']
Does it matter what the names of these branches are? Shouldn't we just preserve all the structure docs pointed to in the values of the versions dict of an active_versions doc?

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    if test_data_file is not None:
Suggestion: This general pattern of switching call behavior to invoke different methods depending on whether a `test_data_file` is passed in or not is prone to error creeping in later -- it's easy to add a piece of controller logic on one of the branches that isn't present in the other and harder to make sure the two paths are actually equivalent. It would be valuable to encapsulate the I/O logic into separate classes so that the `test_data_file` switch looks more like:

```
if test_data_file:
    backend = StaticModuleStoreBackend(test_data_file)
else:
    backend = MongoModuleStoreBackend(connection, database_name)

# Later calls are all the same and look like:
active_versions = backend.get_active_versions(active_version_filter)

#... etc.
```

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +        raise ValueError("Version rention must be at at least 2: origin and active version")
Nitpicks:

* typo: "rention" -> "retention"
* You can use a [`Range option`](http://click.pocoo.org/6/options/#ranges) to do this validation where you specify the `click.option` decorator for this parameter.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +"""
General note: A lot of this code assumes a level of familiarity with what these documents look like. The only detailed documentation that I'm aware of for that is in the module docstring for [xmodule.modulestore.split_mongo.split](https://github.com/edx/edx-platform/blob/master/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py) in edx-platform. A pointer to that documentation, or a corrected version of it (if it's out of date) in this module might help people to better understand and later make fixes/contributions to this code.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +        operation_status = 1
We hardcode failure for this method?

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +            pruned_static_data.append(structure_doc)
I believe the argument `structures_to_remove` here is currently a list. For large values of `structures_to_remove` for both this and the other `prune_structures()` method, it would be potentially much faster for large groups of deletes to pass in a set instead.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    original_dataset[u'structures'] = pruned_static_data
Please return a new data structure instead of mutating the old. This can really complicate debugging.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    """
Please document the data structures being passed in here.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    for structure_doc in structures:
Whenever you need a counter over a for loop, you can use [`enumerate`](https://docs.python.org/2/library/functions.html#enumerate). So it would look like:

```python
for i, structure_doc in enumerate(structures):
    # code here
```

If you need to start at 1 for the counter, you can use the optional `start` arg like:

```python
for i, structure_doc in enumerate(structures, start=1):
    # code here
```

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    available_ids.extend([structure_doc['_id'] for structure_doc in structures])
If `available_ids` is only being used for set inclusion operations, you can make a set out of it like:

```python
available_ids = {structure_doc['_id'] for structure_doc in structures}
```

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +            LOG.debug("{0} was not found in {1}".format(structure_doc["previous_version"], available_ids))
I realize we're addressing perf issues later, but could we flag this log message? From my understanding of how this works, this message could get really large.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +            return structure_doc
For future perf: This will likely get expensive for large values of `structures_list`. We'll probably need to make a lookup dict to map previous versions so that the check can be done in constant time instead of O(n) on each lookup.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    """
This says it's building a tree, but it's always a flat list of ancestors, right? I realize that's still technically a tree, but it might cause confusion.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +        while structure_doc[u'previous_version'] is not None:
Has this been tested with course re-runs?

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +                            versions_to_retain.append(version_tree[-1])
I don't think we ever want to remove the original version, even if it's a meaningless empty course. I thought that the process of relinking meant that we would be modifying the "previous" pointer of the oldest preserved structure to point to "original". The original is used to determine things like common ancestry, and due to the way things are cached, we can get weird results if we change the original and do updates.

For instance, we might still have a cached current structure doc that points to original_1. If the pruning process deletes original_1 and updates the structure docs in MongoDB to point to original_2 as their new "original", then looking for ancestors (e.g. split's `find_ancestor_structures()`) against the cached original will silently fail in a hard to debug way.

2017-08-13 05:25 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    versions_to_remove = list(set(versions_to_remove) - set(versions_to_retain))
Why cast to lists instead of leaving them as sets?

2017-08-13 05:31 UTC, ormsbee commented
Sorry for the delay in review. I'm afraid that almost all of my comments are marked "outdated" because I didn't realize you had done the refactoring of moving all the logic to a new file. Doing a quick glance, it looks like much of the code stayed the same after the move though, so I hope it's still useful to you.

2017-08-15 14:39 UTC, pwnage101 commented
It occurs to me that this repo is python 3, so you should also be able to safely drop all the `u` prefixes before string literals.

2017-08-16 02:15 UTC, eltoncarr commented
@pwnage101, great idea. I was hoping to maintain the status quo.

- [ ] Update string literals

2017-08-16 02:17 UTC, eltoncarr commented
@ormsbee , yes, I made an update with the available suggested changes. I will review your items and respond/provide updates as required

2017-08-16 02:24 UTC, eltoncarr commented on tubular/tests/test_prune_modulestore.py
> +        assert isinstance(file_exists, object)
It's the equivalence of a null check. Thinking more about it, it doesn't seem necessary. 

- [ ] Remove the isinstance assertion in remove_output_file

2017-08-16 02:27 UTC, eltoncarr commented on tubular/tests/test_prune_modulestore.py
> +        self.remove_output_file()
The initial though on this was to use this output file as an input for driving visualization. Inside the UT, it will certainly be short lived and the tempfile package will prove handy.

- [ ] Leverage tempfile package for handling output files in the UT

2017-08-16 02:30 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +"""
- [ ] Add link to [xmodule.modulestore.split_mongo.split](https://github.com/edx/edx-platform/blob/master/common/lib/xmodule/xmodule/modulestore/split_mongo/split.py) in the prune_modulestore.py module docstring

2017-08-16 02:41 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +TARGET_ACTIVE_VERSIONS_KEYS = [u'library', u'draft-branch', u'published-branch']
Initially, we were only privy to those types. My major concern was whether or not other types would require extra handling. Without a definitive answer to that, we took a defensive posture of limiting to what we could explicitly account for instead of making a blanket assumption.

@ormsbee , here are some follow up questions:
1. are there other versions that should be supported? 
2. is there documentation on these versions? 
3. better still, can we confirm that all versions follow the same structures pattern?

2017-08-16 02:44 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +        raise ValueError("Version rention must be at at least 2: origin and active version")
- [ ] Clean up retention typo
- [ ] Leverage click range option to restrict version_retention value

2017-08-16 02:51 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    if test_data_file is not None:
I've simplified by limiting the test data path to UT.

2017-08-16 02:51 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +        LOG.debug("{0} active versions identified.".format(len(active_versions)))
- [ ] Update logging format

2017-08-16 03:21 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +        operation_status = 1
That would be an interesting proposition... It's inadvertent. Apparently, I hadn't noticed these were meant to be treated as exit codes. This has been refactored.

2017-08-16 03:22 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    """
- [ ] Document the data structured passed to the various functions

2017-08-16 03:26 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +            pruned_static_data.append(structure_doc)
- [ ] Switch to sets for handling large lists

2017-08-16 03:28 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    original_dataset[u'structures'] = pruned_static_data
- [ ] return a new data set with updated output

2017-08-16 03:32 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +        structure_filter = get_structures_filter(active_versions_list)
Yes, it is redundant.

- [ ] Switch to evaluating only the active_versions_list filter

2017-08-16 03:41 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +        while structure_doc[u'previous_version'] is not None:
Yes. Course re-runs was key scenario we did a lookout for. In fact, IIRC, course re-runs is what's driving the lower limit of the retention.

- [ ] Augment test dataset with course re-run scenario

2017-08-16 03:43 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +                            versions_to_retain.append(version_tree[-1])
It seems +2 for not making re-linking optional.

- [ ] Remove option for re-linking, making it mandatory

2017-08-16 03:47 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    versions_to_remove = list(set(versions_to_remove) - set(versions_to_retain))
The subsequent operation is to iterate the items. Generally, lists are better at iteration. We could flag this in the perf iteration for evaluation.

- [ ] Flag for performance evaluation

2017-08-16 03:49 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +        filter_enabled = (active_version_filter is not None and len(active_versions) > 0)
- [ ] Fallback to python "truthiness"

2017-08-16 03:51 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    """
This is residue of initial work we did to support user-specified course/library for purging. I pulled that back for next iteration. The intended behavior is to return None if an empty list is passed and the caller is expected to take the appropriate action.

2017-08-16 03:55 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +        active_version_filter = get_active_version_filter(active_version_list)
- [ ] Force get_active_version_filter to return { } when no user filter is provided and simplify query

2017-08-16 04:00 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    return structures_list
Got it.

- [ ]  Simplify generation of structures list with list conversion of the returned mongodb query cursor

2017-08-16 04:01 UTC, eltoncarr-ms commented on tubular/scripts/prune_modulestore.py
> +
- [x] Fallback to python "truthiness"

2017-08-16 21:54 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +            active_versions.append(active_version_doc)
So far, we have accounted only for active versions that have draft-branch, published-branch and library versions. It is a defensive posture to only allow what we have accounted for when considering that there may be others we are not aware of and their handling may be different. Remember, we are talking about pruning structures here. By our calculation, it would be better to err on the side of not including some versions for pruning and only pruning those we explicitly understood and count account for.

So part of this review is to draw on your contextual expertise to callout other versions we should factor in and confirm if they all follow same/similar structures pattern.

2017-08-17 00:50 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +TARGET_ACTIVE_VERSIONS_KEYS = [u'library', u'draft-branch', u'published-branch']
Okay. I think conservative is fine.

1. Those are the only ones we expect. Maybe we can just log if we find a key that we don't anticipate? That way if we do add a new type later on, we'll at least log something so we don't silently skip pruning -- while at the same time preserving the conservative behavior.
2. There is no documentation that I'm aware of aside from the link to source code comments I already mentioned.
3. If you mean for the three types already listed, I can test locally on my devstack if you'd like to help verify, but I'm guessing you folks have already done that for those three. If not, I can do that on Friday (I'm really booked up tomorrow).

Thank you!

2017-08-17 00:57 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    versions_to_remove = list(set(versions_to_remove) - set(versions_to_retain))
FWIW, lists generally give you predictable ordering (though not here, since you're creating it from a set), but they aren't any faster at iteration than sets. I'm fine with doing this in the perf iteration.

2017-08-17 22:44 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +        structures_removal_filter['$in'].append(ObjectId(structure_objectid_str))
Agreed. 

- [ ] switch to inline list generation for the removal filter creation

2017-08-17 22:51 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    for structure_doc in structures:
This is good.

- [ ] Switch to enumerate for iterating structures

2017-08-17 22:53 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +            LOG.debug("{0} was not found in {1}".format(structure_doc["previous_version"], available_ids))
It could, but that'd be in debug mode only.

2017-08-17 22:55 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +            return structure_doc
Yes, I will flag this.

- [ ] flag for performance improvement

2017-08-17 23:01 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    """
- [ ] clarify ancestral list building

2017-08-21 17:29 UTC, doctoryes commented
@eltoncarr One more thing: It's known that simultaneous editing in Studio by multiple users can cause two child structures from a single parent due to a race condition. When this situation happens, one of the children will become the next parent structure while any other children will be dead-end children - never to be used again. All those dead-end children can be safely deleted.

Your script doesn't necessarily need to deal with those dead-end child structures. But I wanted to make you aware of the possibility so that your clean-up code can be written to still function properly even when this situation is encountered.

2017-08-21 18:49 UTC, eltoncarr commented
@doctoryes, thanks for the heads-up. Where applicable, we will take that into account. 

@all, we've covered all the review items and currently running validations. I will be updating the PR in 1-2 days.

2017-08-23 05:38 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    available_ids.extend([structure_doc['_id'] for structure_doc in structures])
- [ ] switch to inline set creation

2017-08-23 05:46 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +TARGET_ACTIVE_VERSIONS_KEYS = [u'library', u'draft-branch', u'published-branch']
- [ ] Adding log line (warn?) for an unexpected active version (ie: not library, draft-branch or published-branch)

2017-08-24 23:44 UTC, eltoncarr commented
Hopefully, all review items have been addressed.

2017-08-28 02:28 UTC, ormsbee commented
Looking this over now.

2017-09-08 22:48 UTC, ormsbee approved these changes
Some nits (optional) and an open question about how we do failure recovery. But nothing blocking this first version from merging.

2017-09-08 22:48 UTC, ormsbee commented on tubular/modulestore.py
> +            output_file_object.write(json.dumps(data).encode())
Nit: If this is a file object, doesn't `json.dump(data, output_file_object)` work here?

2017-09-08 22:48 UTC, ormsbee commented on tubular/modulestore.py
> +        return pruned_structures
Nit: Can be collapsed to a comprehension:

```python
    def prune_structures_static_data(self, structures, structures_to_remove):
        return [sdoc for sdoc in structures if sdoc['_id'] not in structures_to_remove]
```

2017-09-08 22:48 UTC, ormsbee commented on tubular/modulestore.py
> +        assert isinstance(file_exists, object)
This assertion will always pass (`os.path.isfile` always returns a boolean, which is always an object).

2017-09-08 22:48 UTC, ormsbee commented on tubular/modulestore.py
> +        return self.get_query_filter(av_filter)
Nit: Whenever you have an empty list that you then append to in a for-loop, it's often clearer as a comprehension.

2017-09-08 22:48 UTC, ormsbee commented on tubular/modulestore.py
> +            ]
Nit: It's unusual to see a comprehension spread out this much. A more typical form would be:

```python
            unknown_versions = [
                 version for version in active_version['versions']
                 if version not in self.target_active_versions_keys
             ]
```

2017-09-08 22:48 UTC, ormsbee commented on tubular/modulestore.py
> +            resultset = self.db.modulestore.active_versions.find(active_version_filter, fields)
Nit: This conditional is no longer necessary, right?

2017-09-08 22:48 UTC, ormsbee commented on tubular/tests/test_prune_modulestore.py
> +        return found
Nit: You can use `any` and `all` for situations like this where you're iterating a sequence and returning a boolean from it:

```python
def find_structure(self, structures, key):
    return any(structure_doc['_id'] == key for structure_doc in structures)
```

2017-09-08 22:48 UTC, ormsbee commented on tubular/modulestore.py
> +
Nit: You can use `enumerate(activer_versions, start=1)` to get the counter.

2017-09-08 22:48 UTC, ormsbee commented on tubular/scripts/prune_modulestore.py
> +    module_store.relink(structures)
If the script stops running partway through the pruning (or re-linking) parts, do we ever end up in a broken state? Or will re-running the script just work?

2017-09-12 20:39 UTC, doctoryes approved these changes
Just a couple of nits. The script may need some iteration once run against production data. But I'm fine with this version as a starting point. Thanks, @eltoncarr !

2017-09-12 20:39 UTC, doctoryes commented on tubular/scripts/prune_modulestore.py
> +    # we are using live data
Nit: Is this comment necessary?

2017-09-12 20:39 UTC, doctoryes commented on tubular/modulestore.py
> +    def log(self, message, message_type="info"):
Nit: A global `LOG` could be used in both the script and the tests to remove the need for this class-based logging function.

2017-09-19 17:16 UTC, eltoncarr commented on tubular/modulestore.py
> +            output_file_object.write(json.dumps(data).encode())
No, it doesn't.

2017-09-19 17:16 UTC, eltoncarr commented on tubular/modulestore.py
> +        return pruned_structures
Love it

2017-09-19 17:17 UTC, eltoncarr commented on tubular/modulestore.py
> +            resultset = self.db.modulestore.active_versions.find(active_version_filter, fields)
It cost just as much to go either way. However, I though of making this option available in case someone wanted to target a single active_version instead of pruning everything. Additionally, the visualization option we had doesn't deal very well with large data sets. Therefore, this condition primarily supports a validation scenario.

Either way works for me but I lean more towards keeping it and a validation option. Keeping it means a bit more work. Removing it means less work but less opportunity for others to validate.

2017-09-19 17:20 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    module_store.relink(structures)
As is, it will end up in a "broken" state. My thought was to use a snapshot of the data saved to file system after the complete pull from mongo or in between iterations. With this snapshot, yes, it will be completely resumable.

2017-09-19 17:21 UTC, eltoncarr commented on tubular/scripts/prune_modulestore.py
> +    # we are using live data
Not really.

2017-09-19 17:22 UTC, eltoncarr commented on tubular/modulestore.py
> +    def log(self, message, message_type="info"):
Wrapping it provide a bit more control. I personally prefer staying away from use of global variables where possible.

2017-09-26 17:52 UTC, merged