OPS-2372 Retry the message prs in range query if it fails
openedx-unsupported/tubular pull request #191
Opened 2017-10-17 22:02 UTC by coryleeio

2017-10-17 22:17 UTC, feanil commented on tubular/scripts/message_prs_in_range.py
> +        except GithubException:
Are all github exception due to rate limits?  Also, we should print the error before retrying so we know how often we are having to retry.

2017-10-17 22:17 UTC, feanil commented on tubular/scripts/message_prs_in_range.py
> +        except GithubException:
We should also probably back-off exponentially(sleep for more and more time) so that if the services is having issues we don't just hammer it more during the issue.

2017-10-18 15:54 UTC, jdmulloy requested changes

2017-10-18 15:54 UTC, jdmulloy commented on tubular/scripts/message_prs_in_range.py
>          getattr(api, methods[message_type])(pr_number=pull_request, extra_text=extra_text)
I think this line is calling the github api to post the messages to the PRs. Do we need to wrap this with an exception handler and retry logic as well?

2017-10-18 16:01 UTC, jdmulloy commented on tubular/scripts/message_prs_in_range.py
> +        except GithubException:
@feanil Sometimes it's a network timeout. The failure that motivated the ticket is such a case. I think we also need to handle network timeouts on the API calls.

2017-10-18 19:30 UTC, jdmulloy requested changes
This looks like a good solution to me.

Can we also add the timeout exceptions to the backoff decorator? Sometimes the calls to the GitHub API timeout instead of returning a rate limit error.

2017-10-18 20:57 UTC, feanil reviewed
Other than the one comment, this generally looks good.

2017-10-18 20:57 UTC, feanil commented on tubular/scripts/message_prs_in_range.py
> +import backoff
This is a new package right?  In that case it should be added to the requirements file for this repo so it gets correctly installed on the server.

2017-10-18 21:02 UTC, coryleeio commented on tubular/scripts/message_prs_in_range.py
> +import backoff
Nope, it's already in there, line 2

2017-10-18 21:14 UTC, feanil approved these changes

2017-10-19 15:13 UTC, jdmulloy approved these changes

2017-10-19 16:15 UTC, merged