tubular script
openedx-unsupported/tubular pull request #372
Opened 2019-09-19 13:41 UTC by syed-awais-ali

2019-09-19 13:44 UTC, syed-awais-ali commented on tubular/scripts/retrieve_latest_base_ami.py
> +            # parse to get ami for ubuntu_version
Just to single out the ami from here. Will add that

2019-09-19 13:44 UTC, syed-awais-ali commented on tubular/scripts/retrieve_latest_base_ami.py
> +            ubuntu_version = config['base_ami_ubuntu_version']
Should we pass an infile here as well to read the version of ubuntu distro?

2019-09-20 00:06 UTC, coryleeio requested changes

2019-09-20 00:06 UTC, coryleeio commented on tubular/scripts/retrieve_latest_base_ami.py
> +    '--environment', '-e',
You can replace the log statement with something that just prints the ami it found.  It has no need of knowledge of the environment / deployment / or play.  It is only used in logging.

2019-09-20 18:11 UTC, coryleeio commented on tubular/scripts/retrieve_latest_base_ami.py
> +            ubuntu_version = config['base_ami_ubuntu_version']
I would prefer you pass it as an arg if possible, as that is easier to run locally for testing.

But a file is fine too if that is difficult.

2019-09-20 18:12 UTC, coryleeio requested changes

2019-09-20 18:12 UTC, coryleeio commented on tubular/scripts/retrieve_latest_base_ami.py
> +            ubuntu_version = config['base_ami_ubuntu_version']
We discussed and Awais confirmed that we cannot read the config from here.  He will need to pass something in, either an arg or filename.  I would prefer individual arguements as it is easier to use the script by using 

my_script.py --help

and running it locally.

2019-09-25 15:26 UTC, coryleeio requested changes

2019-09-25 15:26 UTC, coryleeio commented on tubular/scripts/retrieve_latest_base_ami.py
> +            ubuntu_version = config['base_ami_ubuntu_version']
config is not defined so this can't run ATM.

2019-09-26 13:29 UTC, syed-awais-ali commented on tubular/scripts/retrieve_latest_base_ami.py
> +            ubuntu_version = config['base_ami_ubuntu_version']
@coryleeio passed this from script in edx-gomatic.

2019-09-27 13:30 UTC, coryleeio submitted a review, later dismissed

2019-09-27 13:30 UTC, coryleeio commented on tubular/scripts/retrieve_latest_base_ami.py
> +            parse_ami = re.search('us-east-1(.+?)hvm', data.content)
parameterize the region here

2019-09-27 13:30 UTC, coryleeio commented on tubular/scripts/retrieve_latest_base_ami.py
> +            parse_ami = re.search('us-east-1(.+?)hvm', data.content)
you can default to us-east-1

2019-10-03 10:05 UTC, syedimranhassan approved these changes

2019-10-03 11:08 UTC, merged