Updating message_pr_in_range logging so we can debug what it cannot find
openedx-unsupported/tubular pull request #402
Opened 2020-02-20 21:16 UTC by coryleeio

2020-02-21 16:51 UTC, feanil requested changes

2020-02-21 16:51 UTC, feanil commented on tubular/scripts/message_prs_in_range.py
> +        LOG.error(u"message_pr_with_type args were: pr_number={0} message_type={1} extra_text={2}", pull_request, message_type, extra_text)
add a `raise` line after this so that we still raise the full original exception after logging.  Otherwise it will not seem like this task failed.

2020-02-24 20:13 UTC, jdmulloy commented on tubular/scripts/message_prs_in_range.py
> +        LOG.error(u"message_pr_with_type args were: pr_number={0} message_type={1} extra_text={2}", pull_request, message_type, extra_text)
@feanil does line 182 address your concern?

2020-02-24 20:17 UTC, feanil approved these changes
Assuming you tested this.

2020-02-25 16:12 UTC, feanil approved these changes

2020-02-25 16:22 UTC, merged