Jdmulloy/isre1377 fix failed pruning 2
openedx-unsupported/tubular pull request #578
Opened 2022-07-07 22:46 UTC by jdmulloy

2022-07-10 20:38 UTC, ormsbee commented
In the middle of reviewing this and had a silly question: Do we know if the nodes that were incorrectly deleted were intermediate structures or original structures? Because as long as the original survived, repairing it would be straightforward. But it gets weird and worse if original docs were deleted.

2022-07-10 21:09 UTC, ormsbee requested changes
Some suggestions and question. Also a thought: Is there a way to connect the missing structure history to a specific course + branch and then show the details of that history to see where it might have gotten messed up?

Thank you.

2022-07-10 21:09 UTC, ormsbee commented on tubular/scripts/structures.py
> +    '--force/--no-force',
Maybe something more specific to the problem like: `--repair-missing`?

2022-07-10 21:09 UTC, ormsbee commented on tubular/splitmongo.py
> +                missing_structure_ids.add(structure_id)
I think this can be simplified to:

```python
missing_structure_ids = structure_ids_to_save - structures.keys()
```

(The empty set declaration of it from line 222 can also be removed in that case.)

2022-07-10 21:09 UTC, ormsbee commented on tubular/splitmongo.py
> +        for missing_structure_id in missing_structure_ids:
This should have comments about what it's trying to do.

2022-07-10 21:09 UTC, ormsbee commented on tubular/splitmongo.py
> +
This would be a good place to abort with a clean error message, if we haven't gotten the special flag that lets us repair the history. We _know_ it's going to blow up in the next batch of code anyway, but we can do a cleaner error message here and exit, and then not have to worry about whether we're in that state or not later on.

2022-07-10 21:09 UTC, ormsbee commented on tubular/splitmongo.py
> +                )
At this point, would it make more sense to leave the code as is, and have some logic above this for loop that looks something like:

```python
# Can't save missing structures.
structure_ids_to_save -= missing_structures_ids
```

(With appropriate logging, of course.)

2022-07-10 21:09 UTC, ormsbee commented on tubular/splitmongo.py
> +            for sid, structure in structures.items():
If you only need the values, you can iterate through `structures.values()` instead of `structures.items()`.

2022-07-10 21:09 UTC, ormsbee commented on tubular/splitmongo.py
> +                    LOG.info(f"structure id: {structure.id}, original_id: {structure.original_id}, previous_id: {structure.previous_id}")
Maybe error level? This kind of information is also nice to have in the details file, but that's not critical.

2022-07-10 21:09 UTC, ormsbee commented on tubular/splitmongo.py
> +                    original_id = structure.original_id
What is this assignment for?

2022-07-10 21:09 UTC, ormsbee commented on tubular/splitmongo.py
> +                    family_ids.append(sid)
Nit: A list comprehension might be useful here.

2022-07-10 21:09 UTC, ormsbee commented on tubular/splitmongo.py
> +                        LOG.debug(f"traversed structure id: {tid}, original_id: {structures[tid].original_id}, previous_id: {structures[tid].previous_id}")
I'm not clear on what this is showing us.

2022-07-11 16:51 UTC, jdmulloy commented on tubular/splitmongo.py
> +                missing_structure_ids.add(structure_id)
Thanks @ormsbee I know there's better ways to do some of these things that are not as easy to understand and it takes so long to run this script that I went with code I knew would work vs code that might fail. I'll implement what I can.

2022-07-11 19:05 UTC, jdmulloy commented on tubular/splitmongo.py
> +                    family_ids.append(sid)
@ormsbee I'm not sure how to do that. It's related to your question about original_id above.

I look through all the structures to find the structure that references the missing_id in previous_id and then I go through again to find all structures with the same original_id so I can traverse the structures to print out the whole chain if debug is turned on. Although it does the work even if it doesn't print.

This structures stuff melts my sleep deprived brain. The output is definitely repetitive.

For instance if there is a chain A->B->C->D->E it will traverse and print for A->B->C->D->E, B->C->D->E, C->D->E, and D->E. It may not really be helpful. I'm just trying to make something useful if we run into this again.

2022-12-16 22:30 UTC, merged