feat!: upgrade boto code to boto3.
openedx-unsupported/tubular pull request #657
Opened 2023-05-14 21:04 UTC by awais786

part4:

2023-05-15 15:16 UTC, awais786 commented on tubular/admin/boto_to_add_ingress.py
> +    go_agent_security_group = ec2.create_security_group(
Need some expert review here.

2023-05-15 15:16 UTC, awais786 commented on tubular/admin/boto_to_add_ingress.py
> +                ec2.authorize_security_group_ingress(
Need expert review here.

2023-05-18 19:22 UTC, matthugs requested changes

2023-05-18 19:22 UTC, matthugs commented on tubular/admin/boto_to_add_ingress.py
I can't find uses of this file. I think we may be able to delete it rather than converting it.

2023-05-19 10:23 UTC, awais786 commented
@dianakhuang your opinion about this file. If it has no usage i can delete it.

2023-05-19 12:13 UTC, closed without merging